[run]
init_cmds = [["./peach", "web"]]
watch_all = true
watch_dirs = [
	"$WORKDIR/cmd",
	"$WORKDIR/models",
	"$WORKDIR/routes"
]
watch_exts = [".go", ".ini"]
build_delay = 1500
cmds = [
	["go", "install"],
	["go", "build"],
	["./peach", "web"]
]